import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/compnents/navbar/Navbar"
import Footer from "@/compnents/footer/Footer"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "localhost3000",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="cont">
        <Navbar />
        {children}
        <Footer />
        </div>
      </body>
    </html>
  );
}